### ISSUE TITLE
is-set 'return' outside of function (12:1)

### ISSUE THREAD

**Issue by hckhanh** [inspect-js/is-set#3]
I really don't know what is going on when I upgrade my packages. Then I get this error

```sh
ERROR in ./node_modules/is-map/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: node_modules\is-map\index.js: 'return' outside of function (12:1)
```

**Comment by ljharb** [comment]
`return` is perfectly valid at the top level of any CJS module; are you using some kind of bundler that isn't properly wrapping CJS modules?

**Comment by shilman** [comment]
I think this might be due to a Storybook bug. Investigating now.
